openapi: 3.0.3
info:
  title: "API JouerFlux"
  version: "1.0.0"
  description: "Documentation de l'API pour l'application JouerFlux"
servers:
  - url: http://localhost:5000
    description: Rest Server showing Swagger and Connexion capability
paths:
  /firewalls:
    get:
      operationId: firewall.getAll
      tags:
        - Firewalls
      summary: Récupère la liste de tous les firewalls.
      description: Récupère la liste de tous les firewalls.
      responses:
        "200": 
          description: Récupère la liste de tous les firewalls.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Firewall"
    post:
      operationId: firewall.create
      tags:
        - Firewall
      summary: Créé un nouveau firewall.
      description: Créé un nouveau firewall.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Firewall"
      responses:
        "201":
          description: Création réussie
  /firewalls/{id}:
    get:
      operationId: firewall.get
      tags:
        - Firewall
      summary: Récupère le firewall d'ID donné
      description: Récupère le firewall d'ID donné
      parameters:
        - name: id
          in: path
          description: Firewall ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200": 
          description: Récupère le firewall d'ID donné
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Firewall"
    delete:
      operationId: firewall.delete
      tags:
        - Firewall
      summary: Supprime le firewall d'ID donné
      description: Supprime le firewall d'ID donné
      parameters:
        - name: id
          in: path
          description: Firewall ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200": 
          description: Suppression réussie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Firewall"
    put:
      operationId: firewall.update
      tags:
        - Firewall
      summary: Met à jour un firewall d'ID donné
      description: Met à jour un firewall d'ID donné
      parameters:
        - name: id
          in: path
          description: Firewall ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Firewall"
      responses:
        "200": 
          description: Mise à jour réussie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Firewall"
  /policies:
    get:
      operationId: policy.getAll
      tags:
        - Policies
      summary: Récupère la liste de toutes les policies.
      description: Récupère la liste de toutes les policies.
      responses:
        "200": 
          description: Récupère la liste de toutes les policies.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Policy"
    post:
      operationId: policy.create
      tags:
        - Policy
      summary: Créé un nouveau policy.
      description: Créé un nouveau policy.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Policy"
      responses:
        "201":
          description: Création réussie
  /policies/{id}:
    get:
      operationId: policy.get
      tags:
        - Policy
      summary: Récupère la policy d'ID donné
      description: Récupère la policy d'ID donné
      parameters:
        - name: id
          in: path
          description: Policy ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200": 
          description: Récupère la policy d'ID donné
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Policy"
    delete:
      operationId: policy.delete
      tags:
        - Policy
      summary: Supprime la policy d'ID donné
      description: Supprime la policy d'ID donné
      parameters:
        - name: id
          in: path
          description: Policy ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200": 
          description: Suppression réussie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Policy"
    put:
      operationId: policy.update
      tags:
        - Policy
      summary: Met à jour une policy d'ID donné
      description: Met à jour une policy d'ID donné
      parameters:
        - name: id
          in: path
          description: Policy ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Policy"
      responses:
        "200": 
          description: Mise à jour réussie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Policy"
  /rules:
    get:
      operationId: rule.getAll
      tags:
        - Rules
      summary: Récupère la liste de toutes les rules.
      description: Récupère la liste de toutes les rules.
      responses:
        "200": 
          description: Récupère la liste de toutes les rules.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Rule"
    post:
      operationId: rule.create
      tags:
        - Rule
      summary: Créé une nouvelle rule.
      description: Créé une nouvelle rule.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Rule"
      responses:
        "201":
          description: Création réussie
  /rules/{id}:
    get:
      operationId: rule.get
      tags:
        - Rule
      summary: Récupère la rule d'ID donné
      description: Récupère la rule d'ID donné
      parameters:
        - name: id
          in: path
          description: Rule ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200": 
          description: Récupère la rule d'ID donné
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Rule"
    delete:
      operationId: rule.delete
      tags:
        - Rule
      summary: Supprime la rule d'ID donné
      description: Supprime la rule d'ID donné
      parameters:
        - name: id
          in: path
          description: Rule ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200": 
          description: Suppression réussie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Rule"
    put:
      operationId: rule.update
      tags:
        - Rule
      summary: Met à jour une rule d'ID donné
      description: Met à jour une rule d'ID donné
      parameters:
        - name: id
          in: path
          description: Rule ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Rule"
      responses:
        "200": 
          description: Mise à jour réussie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Rule"

components:
  schemas:
    Firewall:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        policies:
          type: array
          items:
            type: string
    Policy:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        firewall_id:
          type: integer
          format: int64
    Rule:
      type: object
      properties:
        id:
          type: integer
          format: int64
        rule_type:
          type: string
        source:
          type: string
        destination:
          type: string
        policy_id:
          type: integer
          format: int64
